const TOTAL_CIRCLES=94
const INIT_SELECTED_CIRCLE=Math.floor(Math.random() * TOTAL_CIRCLES);
const TIME_COUNT=30
const CORRECT_KEY=true;
const WRONG_KEY=false

export {
    TOTAL_CIRCLES,
    INIT_SELECTED_CIRCLE,
    TIME_COUNT,
    CORRECT_KEY,
    WRONG_KEY
}